# crypto-signal-name: 🚀 Telegram Signal Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # هر 30 دقیقه
  workflow_dispatch:        # دکمه اجرای دستی

jobs:
  run-signal-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 دریافت کد
      uses: actions/checkout@v3
      
    - name: 🐍 نصب پایتون
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 📦 نصب کتابخانه‌ها
      run: |
        pip install --upgrade pip
        pip install requests pandas pandas_ta ccxt
        
    - name: 🤖 اجرای ربات سیگنال
      run: run: python main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}-2
